apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: configmap-example
        # An array of keys from the ConfigMap to create as files
        items:
          - key: key1
            path: "path/to/config/key1"