apiVersion: v1
kind: Pod
metadata:
  name: downward-test-pod-volume
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
    - name: test-container
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - name: info
          mountPath: /downward
          readOnly: false
  volumes:
    - name: info
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations